# Generated by Django 4.2 on 2023-04-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.TextField()),
                ('order_id', models.TextField()),
                ('email', models.TextField(default='N/A')),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.TextField()),
                ('product_name', models.TextField()),
                ('category', models.TextField()),
                ('brand', models.TextField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
