# Generated by Django 4.2 on 2023-04-13 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.TextField()),
                ('customer_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.customer')),
            ],
        ),
    ]
